version: "3"

services:
  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    networks:
      - public

  consumer:
    build: ./consumer
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  db:
    image: mvertes/alpine-mongo
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:alpine
    networks:
      - public
      - backend

networks:
  public:
  
  backend:
